### PR TITLE
Add "sensitive" resource and data source

### PR DESCRIPTION
**Pull request by zhimsel**
These are functionally identical, but masks the inputs/outputs.

Confirm that tests pass as expected. Also tested functionally with internal resources.

Closes https://github.com/hashicorp/terraform-provider-null/issues/38

Conflicts with https://github.com/hashicorp/terraform-provider-null/pull/48

### CODE REVIEW

**Comment by zhimsel** [comment]
Rebased against latest `main`.

**Comment by slawekwww** [comment]
When new module would be released with those changes? 👍 
I would like to use them immediately as it blocks to remove resource using local-exec provisioner (sometimes it is the only way) once sensitive data is required.

**Comment by fizzamahdi** [comment]
upgrading some terraform projects to version 0.13 and need to set some sensitive values in the triggers to overcome this error 
```
Destroy-time provisioners and their connection configurations may only
reference attributes of the related resource, via 'self', 'count.index', or
'each.key'.
```

Could really use this change!

**Comment by zhimsel** [comment]
Closing as per the reasons in https://github.com/hashicorp/terraform-provider-external/pull/55

I've confirmed that the data source itself doesn't show up in plans.

**Pull request closed without merging**
