### PR TITLE
Change to doc generation

### PR DESCRIPTION
**Pull request by paultyng**

### CODE REVIEW

**Comment by paultyng** [comment]
Reviewing just fa32e95f00f347c259dc8d645500a46a5acd5007 gives a better diff on how the docs actually changed.

**Comment by kmoe** [comment]
Is removing `vendor` related to doc generation? If not, could we move that to another PR or create an issue? `-mod=vendor` is mentioned in a number of places (e.g. Makefile) and I want to make sure we clean up consistently in all providers if we're doing this.

**Comment by paultyng** [comment]
Mostly that the plugin doc generation adds a number of dependencies, so the PR will be huge in additions or huge in subtractions 😄

**Review by kmoe — APPROVED** [review]
Docs generated look good. Please add the doc generation command to the dev section of the README.

**Comment by kmoe** [comment]
Adding a task elsewhere for cleaning up `-mod=vendor` and the like in all stdlib providers.

**Pull request merged**
